# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6f5ac7411c6133caf4cddf7efb95d1fbdb84fb1630f76789eb3fe6a742f7305be3afdc791d441ba16e3044140296c1ba1be01e45d73f3cf74ac8aa0891c4154

test:
  secret_key_base: 187e771c3ffc4cfa86734f27105a45e7da243b11b6850ee72c05b2ce1669c31c4b22a9f5135d092c82d91a2ba6ca295480c72ddd11acdf09b2ec5289a6ab34ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
