# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ebc80c44d8361da0579d0b3031856b2551f435e26762e2e6ca1320764ddf284fde6d76ca289ea1b351a2d9dbdce1dfd9390152cd3c718c5198cbd4fb50961f4

test:
  secret_key_base: d2bda73f5dc3e3e956567b64f1b31d68db7bb6a69a7328261604c93614c730fa041ddc5e149a4fbd7253155c478752612f98e429b56131cfb426b3d57c999784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
