# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e53836ff22c20a31c916e5fe562615655005b2f6aefbd225d0f96fc591ce4d1b04d6b0b34265e7a05f11f03db9cf13544bcb5b08dd2d7c67ab0a268160b882b0

test:
  secret_key_base: 2ba4fbf8a93c20ef7c4ab881e90280386e020eebdfbdb0459f4b5c174ee4d81af33f3b16ccc04b5d92cd4d99debce65eeb289788dca6cc07acaf7b1f81904e25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
